### ISSUE TITLE
Disc Priest WOTLK Classic 

### ISSUE THREAD

**Issue by niknak6** [2072/Decursive#10]
Hello,

As a disc priest in wotlk classic, decursive is not detecting that I am able to dispel magic. I can dispel disease fine, however, magic effects do not show. In the settings, the option to check magic is grayed out. Any insight?

**Comment by 2072** [comment]
Please see this thread on wowace: https://www.wowace.com/projects/decursive/issues/226

**Comment by 2072** [comment]
I've just released a new alpha version that should fix this.
