### ISSUE TITLE
LUA Error Fatally Breaking Decursive

### ISSUE THREAD

**Issue by Colerain** [2072/Decursive#12]
```
49x Decursive/Dcr_DebuffsFrame.lua:1487: attempt to call upvalue 'GetItemCooldown' (a nil value)
[string "@Decursive/Dcr_DebuffsFrame.lua"]:1487: in function `SetColor'
[string "@Decursive/Dcr_DebuffsFrame.lua"]:1186: in function <Decursive/Dcr_DebuffsFrame.lua:1144>
[string "@Decursive/Dcr_utils.lua"]:878: in function `func'
[string "@Decursive/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Decursive/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
InCombatSkipped
```

**Comment by Colerain** [comment]
This is still happening and it's often a fatal bug after awhile.

**Comment by 2072** [comment]
can you provide me with the full Decursive debug report? I need it to get the context (precise wow version etc...).

**Comment by Colerain** [comment]
2.7.9  MAGE(39)  CT: 29.1640 D: Sun Apr  2 10:25:27 2023 enUS BG BDTHFAd: nil nDrE: 1 Embeded: true W: 1 (LA: 63 TAMU: 106583) TA: 0 NDRTA: 0 BUIE: 0 TI: [dc:4, lc:4, y:0, LEBY:0, LB:1, TTE:8] (3.4.1, 48632, Mar 16 2023, 30401)

*****************

27.1600 (tr:'' ca:'false' icl:'false' h66_w66-164fps-Orgrimmar): Now checking the event management library... -|count: 1

*****************

27.6610 (tr:'DcrDiagOneTimeEvent' ca:'false' icl:'false' h66_w66-162fps-Orgrimmar): delayed call executed -|count: 1

*****************

29.1640 (tr:'' ca:'false' icl:'false' h66_w66-159fps-Orgrimmar): Event library functionning properly, Everything seems to be OK -|count: 1

-- --

Spells assignments:

    Prio 1: - CURSE - (*%s1) -> Remove Curse

    Prio 2: - POISON - (*%s2) -> Powerful Anti-Venom

    Prio 3: - MAGIC - (shift-%s1) -> Major Recombobulator
-- --
Custom spells configuration:

    Powerful Anti-Venom (id: -19440) - ON - PLAYER - ITEM - B: 13 - Ts: 
  {
    [1] = [8],
  } - UF: 
  {
    [8] = [2],
  } - Macro: false

    Major Recombobulator (id: -18637) - ON - PLAYER - ITEM - B: 10 - Ts: 
  {
    [1] = [1],
  } - UF: nil - Macro: false

    Minor Recombobulator (id: -4381) - ON - PLAYER - ITEM - B: 10 - Ts: 
  {
    [1] = [1],
  } - UF: nil - Macro: false

-- --
Decursive known spells:
(left and right side should be 'matching')

  {
    [DCR_LOC_MINDVISION] = [Mind Vision],
    [SPELL_DISPELL_MAGIC] = [Dispel Magic],
    [SPELL_COUNTERSPELL] = [Counterspell],
    [Lesser Invisibility] = [Lesser Invisibility],
    [ANCIENTHYSTERIA] = [Ancient Terror],
    [SPELL_HEX] = [Hex],
    [MUTATINGINJECTION] = [Mutating Injection],
    [SPELL_CLEANSE] = [Cleanse],
    [SPELL_ABOLISH_POISON] = [Abolish Poison],
    [Banish] = [Banish],
    [SPELL_CURE_POISON_SHAMAN] = [Cure Toxins],
    [SPELL_ABOLISH_DISEASE] = [Abolish Disease],
    [IGNITE] = [Ignite Mana],
    [SPELL_DISPELL_MAGIC_PRIEST_R2] = [Dispel Magic],
    [Stealth] = [Stealth],
    [MAGMASHAKLES] = [Magma Shackles],
    [SPELL_PURGE] = [Purge],
    [SPELL_FEAR] = [Fear],
    [TAINTEDMIND] = [Tainted Mind],
    [DREAMLESSSLEEP] = [Dreamless Sleep],
    [WIDOWSEMBRACE] = [Widow's Embrace],
    [SPELL_PURIFY] = [Purify],
    [SPELL_CURE_DISEASE_PRIEST] = [Cure Disease],
    [DCR_LOC_SILENCE] = [Silence],
    [DUSTCLOUD] = [Dust Cloud],
    [Frost Trap Aura] = [Frost Trap Aura],
    [SPELL_REMOVE_CURSE_MAGE] = [Remove Curse],
    [SPELL_POLYMORPH] = [Polymorph],
    [CLEANSE_SPIRIT] = [Cleanse Spirit],
    [SPELL_TRANQUILIZING_SHOT] = [Tranquilizing Shot],
    [SPELL_WILL_OF_THE_FORSAKEN] = [Will of the Forsaken],
    [GDREAMLESSSLEEP] = [Greater Dreamless Sleep],
    [DELUSIONOFJINDO] = [Delusions of Jin'do],
    [SPELL_REMOVE_CURSE_DRUID] = [Remove Curse],
    [Prowl] = [Prowl],
    [SONICBURST] = [Sonic Burst],
    [SPELL_CURE_POISON_DRUID] = [Cure Poison],
    [Shadowmeld] = [Shadowmeld],
    [PET_DEVOUR_MAGIC] = [Devour Magic],
    [TALENT_BODY_AND_SOUL] = [Body and Soul],
    [CRIPLES] = [Cripple],
  }
-- --Script ran too long errors:

  {
    [total] = [0],
  }
-- --

Loaded Addons:

!BugGrabber (N/A)[25]{MU: 64}
!Swatter (3.4.6921 (SwimmingSeadragon))[90]{MU: 324}
AdvancedInterfaceOptions (1.8.5)[4]{MU: 1122}
Auctionator (10.0.44)[15]{MU: 3485}
BagBrother (N/A)[144]{MU: 215}
Bagnon (10.0.16)[140]{MU: 840}
BasicMinimap (v10.0.9)[17]{MU: 976}
BattleGroundEnemies (10.0.2.6)[20]{MU: 7549}
BattleInfo (@project-version)[19]{MU: 87}
BeanCounter (3.4.6933 (SwimmingSeadragon))[22]{MU: 1726}
BetterVendorPrice (v1.18.07)[23]{MU: 211}
BigDebuffs (v11.20)[24]{MU: 2724}
BugSack (v10.0.4)[26]{MU: 129}
Capping (v10.0.15)[27]{MU: 187}
Clique (v3.4.15-release)[29]{MU: 338}
Decursive (2.7.9)[30]{MU: 1149}
DejaChat (Uv3)[31]{MU: 14}
Diminish (v2.5.9)[40]{MU: 139}
Diminish_Options (v2.5.9)[41]{MU: 172}
Dominos (10.0.22)[42]{MU: 604}
Dominos_Cast (N/A)[43]{MU: 110}
Dominos_Progress (N/A)[45]{MU: 99}
Dominos_Roll (N/A)[46]{MU: 8}
Doom_CooldownPulse (N/A)[47]{MU: 51}
DropTheCheapestThing (v2023.2)[48]{MU: 175}
Enchantrix (3.4.6942 (SwimmingSeadragon))[49]{MU: 1107}
Enchantrix-Barker (3.4.6917 (SwimmingSeadragon))[50]{MU: 424}
EnhanceBattlefieldMinimap (v141)[51]{MU: 563}
ErrorFilter (v3.8)[52]{MU: 338}
ExtendedCharacterStats (3.0.9)[53]{MU: 673}
Gnosis (4.97)[54]{MU: 3884}
GrizzlySharedMedia (1)[55]{MU: 107}
Informant (3.4.6934 (SwimmingSeadragon))[57]{MU: 8339}
ItemRack (3.75)[58]{MU: 321}
LibSharedMedia-3.0 (3.0-132)[61]{MU: 171}
MBB (1.2.1)[69]{MU: 91}
MRT (4720)[66]{MU: 4779}
MacroToolkit (v2.0.2)[62]{MU: 1019}
MacroToolkitIcons (v2.0.2)[63]{MU: 2185}
MaxCam (v2.6.1)[65]{MU: 22}
MikScrollingBattleText (5.7.154)[68]{MU: 616}
Myslot (v5.8.2-v3.4.0)[70]{MU: 491}
NameplateCooldowns (30401.0-release)[72]{MU: 1260}
NovaInstanceTracker (1.40)[73]{MU: 3821}
NovaWorldBuffs (2.46)[74]{MU: 2517}
OmniBar (v14.2)[75]{MU: 9921}
OmniCC (10.0.5)[76]{MU: 169}
Plater (Plater-v555-Wrath)[78]{MU: 7493}
Prat-3.0 (3.9.24)[79]{MU: 1612}
Prat-3.0_Libraries (N/A)[80]{MU: 92}
Precognito (1.7)[81]{MU: 196}
SafeQueue (v8.2)[84]{MU: 29}
Scorpio (v179)[1]{MU: 18249}
ShadowedUnitFrames (v4.3.4-classic)[86]{MU: 2465}
SlideBar (3.4.6919 (SwimmingSeadragon))[87]{MU: 57}
SpeedyAutoLoot (2.2.10)[109]{MU: 23}
Spy (3.1.4)[88]{MU: 2154}
Stubby (3.4.6920 (SwimmingSeadragon))[89]{MU: 82}
TipTacItemRef (22.09.02)[95]{MU: 525}
WIM (3.10.9)[108]{MU: 2103}
WeakAuras (5.4.4)[103]{MU: 6104}
tullaRange (10.0.11)[98]{MU: 34}
unitscan (v3.0.1)[100]{MU: 20}
-- --

**Comment by 2072** [comment]
Thanks for the detail. This should be fixed in the latest alpha released ~1 hour ago. This problem only happened in WotLK when using objects.

**Comment by Colerain** [comment]
It's working just fine now. Thanks for the update.

Are you Archarodim? I put a request for a whitelist on the Curseforge page two months ago and they self assigned. I just put another feature request in. More important than even the whitelist, which can at least be fixed with a blacklist workaround.
