### ISSUE TITLE
Affliction Priority Doesn't Stick If Item Removed

### ISSUE THREAD

**Issue by Colerain** [2072/Decursive#14]
The use case is Major Recombobulator in WotLK Classic. I want to cure Polymorph as the highest priority. When I assign it the highest priority, and then unequip the item, it removes it from the priority list. That's fine, but when I re-equip the item, it should remember the priority that I assigned to it. Currently it will just assume the lowest priority.

**Comment by 2072** [comment]
It should be fixed in the latest alpha version, you can grab it on wowace: https://www.wowace.com/projects/decursive/files
