### ISSUE TITLE
[Retail] Curses not tracked with Shaman Improved Purify Spirit

### ISSUE THREAD

**Issue by chrisleaman** [2072/Decursive#15]
I'm not sure if I'm doing something wrong, but when I take Improved Purify Spirit on my Shaman in retail, the option to track curses is not available. I see https://github.com/2072/Decursive/commit/8bf1557c022f9b6003dc65acbd5ecdf6e2aef85e was meant to address this, but it looks like there still might be issues. I'm running the latest `v2.7.9.2` release.

I've been a long time user of decursive, so just also wanted to say a big thank you for the time and work you've put in for this! 🙏

![20230616_105823_homepc](https://github.com/2072/Decursive/assets/7591552/2fada4ef-40b6-4d40-9702-799c1c0affe3)

![20230616_105840_homepc](https://github.com/2072/Decursive/assets/7591552/40b08ad2-f953-4cb3-a0df-d2bc09430d7f)

![20230616_110041_homepc](https://github.com/2072/Decursive/assets/7591552/c23bec32-302f-4d21-a6c0-17e4b52e682e)

**Comment by 2072** [comment]
Thanks for the detailed report. This is fixed in the latest alpha version.
