### ISSUE TITLE
Bug Grabber Indexing a NIL

### ISSUE THREAD

**Issue by Bonesly** [2072/Decursive#17]
There was an update to WoW at my end-of-gaming on 19-Sep-2023.  When I logged in today (20-Sep-2023), I'm seeing this error.

![image](https://github.com/2072/Decursive/assets/113857203/d3f38d5b-e254-4032-bf18-7046cec60933)

BugGrabber.lua:319: attempt to index local 'stack' (a nil value)

**Comment by teelolws** [comment]
Looks like there was an issue with buggrabber that has been fixed. Need Decursive to update its buggrabber library: https://www.curseforge.com/wow/addons/bug-grabber/files/4761435

**Comment by 2072** [comment]
This should be fixed in latest alpha release for all versions.
