### ISSUE TITLE
Several healers dispel is not working with 10.2.6

### ISSUE THREAD

**Issue by jardragon901** [2072/Decursive#21]
Version: Retail, 10.2.6
Decursive version: 2.7.16 (latest)

Every healer but pally and monk has had decursive broken for them, it's probably the change they made to combine the spells when you take the improved version in the talent tree from what i can see.

> Macros that use the non-healer versions of dispels will now override the ability with the healer dispel variant if the player is in a healer specialization. This applies to Discipline, Holy Priest, Holy Paladin, Restoration Druid, and Restoration Shaman. Mistweaver Monk and Preservation Evoker already had this functionality.

**Comment by 2072** [comment]
what the f***k did they do... This will be painful to debug, they seem to have used a bandaid hack à la microsoft to implement their "feature"...  🤦

There are several hours of work to "fix" this, I first need to reverse engineer what they did, then find a workaround and implement it... this will take days...

Thanks for making this ticket and pointing me in the right direction

**Comment by Meivyn** [comment]
The problem seems to be that `IsSpellKnown` is returning false for those spells. I did the debug part.

**Comment by 2072** [comment]
Thanks for the quick fix! I did not know about the  IsSpellKnownOrOverridesKnown() function...
