### ISSUE TITLE
Cataclysm version?

### ISSUE THREAD

**Issue by ForgeGit** [2072/Decursive#23]
WoW Classic just got updated from WOTLK to CATA (4.4.0.54481).

Are there any plans to update the addon on Curseforge to Cataclysm?

**Comment by Kirschie** [comment]
I want to +1 this issue. I can see I need to decurse a target in the UI, the UI indicates a poison/curse/disease etc... but when attempting to cure that ailment I get the errors below. So far this has happened in Heroic AN, and Heroic CoS. I have been able to cure in other dungeons. Not sure if spell ids changed. Will try to get more details on what I can't decurse. 

![image](https://github.com/2072/Decursive/assets/25411412/19686232-6a98-45f7-a940-3a7a2ffb80d1)

**Comment by 2072** [comment]
I've just made a new release that should fix Cataclysm related issues, please update this issue if you find anything else

**Comment by Kirschie** [comment]
Thank you testing tonight and will report any feedback.

**Comment by dh-harald** [comment]
Hi,

Druid with Nature's Cure nit highlighting the magic.
