### ISSUE TITLE
Druid magic dispel

### ISSUE THREAD

**Issue by Bagiddi** [2072/Decursive#24]
Resto druid gets the Nature's Cure talent which allows them to remove magic effects from allies in Cataclysm pre-patch but as far as I can tell Decursive does not support this. I attempted to go into the settings to tell it to track magic but the square was "greyed out" and can't be selected. Using most current version of addon I can find.
![decursive1](https://github.com/2072/Decursive/assets/168884320/763c479e-93b8-4cb1-a26f-db5a5dc7ed4e)
![Decursive2](https://github.com/2072/Decursive/assets/168884320/431c5ee3-75e1-4208-8eae-9132a4b49144)
![Decursive3](https://github.com/2072/Decursive/assets/168884320/6b92f90a-88b6-412d-802a-170fea8e487b)

**Comment by wendsell** [comment]
I am having the same issue on my druid.

**Comment by Budgethealer** [comment]
same

**Comment by 2072** [comment]
Thanks for reporting, this is fixed in the latest alpha please test and report back to confirm.

**Comment by Bagiddi** [comment]
Can confirm as of version 2.7.18-1 it does appear to be working with Nature's Cure.
