### ISSUE TITLE
SoD Mages can't dispel magic effect with Advanced Warding rune.

### ISSUE THREAD

**Issue by CodyCenters** [2072/Decursive#25]
In Season of Discovery, the helm rune Advanced Warding changes Mages spell Remove Lesser Curse to Remove Greater Curse, which also removes 1 harmful magic effect from an ally.

The decursive frame in groups/raids does not allow us to remove Magic effects.

**Comment by 2072** [comment]
This will be implemented in a later release, in the meantime, follow the
instructions here #269 dispell types - override greyed out boxes - Issues -
Decursive - Addons - Projects - WowAce
<https://www.wowace.com/projects/decursive/issues/269> to add the spell
through the custom spell interface.
