### ISSUE TITLE
Dispel abilities for Restoration Monks have been updated.

### ISSUE THREAD

**Issue by hexianggui** [2072/Decursive#28]
The name of the Monk's dispel spell in World of Warcraft has changed from 'Cleansing Brew' to 'Enhanced Cleansing Brew.' I'm not sure how to set it up.
I don't know how to customize the dispel Mage (if customization is possible). If customization is not available, I think this is a good suggestion. Thank you
New spell ID: 388874
![Uploading 屏幕截图 2024-08-30 221602.png…]()

**Comment by hexianggui** [comment]
I found the customization option, define the spell and check it! Great! Thank you!

**Comment by 2072** [comment]
Thanks for the report, I'll add the spell
