### ISSUE TITLE
Xal'atath's Bargain: Devour Priest Dispel

### ISSUE THREAD

**Issue by nbluis** [2072/Decursive#30]
Hello, first of all thank you for the amazing work with decursive.

For the first time in retail we had the Xal'atath's Bargain: Devour affix. A healing shield that can be dispelled or healed. I noticed playing with my priest that the decursive does not indicate anything to be dispelled on my allies.

The debug applied is [Void Rift](https://www.wowhead.com/spell=440313/void-rift).

I have not tested it, but I believe that since it is something relatively new, other classes may be presenting the same situation.

**Comment by 2072** [comment]
Hello, thank you for the detailed information. On wowhead it is said that the effect is a buff (not a debuff), can you confirm this? (if that's the case then it's normal that Decursive is not picking it up and I'll need to do something special)

**Comment by Davidgil17** [comment]
Hello, as a mage this was not coming up for me on Decursive either. But, I was able to remove this with Remove Curse.

**Comment by cykotix** [comment]
[WoWCombatLog-101024_222217.zip](https://github.com/user-attachments/files/17337269/WoWCombatLog-101024_222217.zip)

Combat log attached.  Few runs in here that should show the buff and groups successfully removing it as well.  Usually a Shaman with a Cleaning Totem and I believe Pally cleanse as well.

**Comment by 2072** [comment]
Ok this should be working in the latest alpha version available at Wowace: https://www.wowace.com/projects/decursive/files please confirm that it works.

**Comment by PatrickLahniCCHMC** [comment]
Thanks for fixing this.  We won't be able to test this until the Devour affix is selected again for mythics.  Since Devour was last week, I assume it might be 2 more weeks before we can confirm this works.  I'm relatively new to mythics unless the affix rotation happens randomly or predictably, that might change the feedback timeline.

**Comment by cykotix** [comment]
Can confirm it works on my priest.  Haven't tested mage yet.

**Comment by cykotix** [comment]
Works for mage as well.  I assume this is safe to push.

**Comment by 2072** [comment]
Awesome! Thanks for confirming it works.
