### ISSUE TITLE
[Feature] Click-through MUF when inactive

### ISSUE THREAD

**Issue by DoctorBak** [2072/Decursive#4]
Hi, Classic player here.
Would it be possible to add the option to click through the Micro-Unit Frames when there is nothing to dispel? That would allow the MUF to be placed over other interactive unit frames such as Grid and further reduce some mouse movements.
If that was already a thing, I'm sorry but I couldn't make it work.

**Comment by 2072** [comment]
I'm not sure if this is possible, unit frames are quite restricted. Do you know of another add-on that achieves that kind of feature?
