### ISSUE TITLE
GetBackdrop  error

### ISSUE THREAD

**Issue by Roneasaurus** [2072/Decursive#8]
**### _this error is coming up since patch 9.1.5 of warcraft went live._**

Message: ...ce\AddOns\Decursive\Libs\LibQTip-1.0\LibQTip-1.0-48.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Wed Nov  3 09:21:02 2021
Count: 6
Stack: ...ce\AddOns\Decursive\Libs\LibQTip-1.0\LibQTip-1.0-48.lua:543: attempt to call method 'GetBackdrop' (a nil value)

Locals: 

**_### and this is the 2nd error message._**

Message: ...ce\AddOns\Decursive\Libs\LibQTip-1.0\LibQTip-1.0-48.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Wed Nov  3 09:28:37 2021
Count: 1
Stack: ...ce\AddOns\Decursive\Libs\LibQTip-1.0\LibQTip-1.0-48.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua"]:886: in function `OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: self = <table> {
 UpdateMUFUnit = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:700
 OnEnter = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:748
 MaxUnit = 80
 MFUsableNumber = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:233
 SavePos = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:645
 OnPostClick = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:1018
 UnitsDebuffedInRange = 0
 Create = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:207
 Show = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:162
 Delayed_MFsDisplay_Update = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:320
 RegisterMUFcolors = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:172
 OnCornerEnter = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:902
 metatable = <table> {
 }
 Place = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:511
 GetMUFAnchor = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:278
 Frame = DcrMUFsContainer {
 }
 GetFarthestVerticalMUF = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:177
 OnAttributeChanged = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:1839
 OnPreClick = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:935
 new = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:96
 Delayed_Force_FullUpdate = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:437
 SetScale = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:689
 Number = 1
 OnLoad = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:929
 DraggingHandle = false
 GetHelperAnchor = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:299
 ResetAllPositions = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:238
 ToString = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:202
 ExistingPerUNIT = <table> {
 }
 OnCornerLeave = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:899
 OnLeave = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:891
 prototype = <table> {
 }
 MFsDisplay_Update = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:327
 UnitToMUF = <table> {
 }
 Force_FullUpdate = <function> defined @Interface\AddOns\Decursive\Dcr_DebuffsFrame.lua:443
 UnitShown = 1
}
frame = <unnamed> {
 0 = <userdata>
 Object = <table> {
 }
}
MF = <table> {
 LastAttribUpdate = 944654.670000
 Debuff1Prio = false
 UpdateCountDown = 1
 OuterTexture3 = <unnamed> {
 }
 UnitClass = "MAGE"
 UpdateCD = 0
 PrevDebuff1Prio = false
 usedAttributes = <table> {
 }
 CurrUnit = "player"
 NormalAlpha = 0.350000
 Frame = <unnamed> {
 }
 FirstDebuffType = false
 FrameNum = 1
 Debuffs = <table> {
 }
 Color = <table> {
 }
 CenterText = false
 CenterFontString = <unnamed> {
 }
 CooldownFrame = <unnamed> {
 }
 OuterTexture2 = <unnamed> {
 }
 ID = 1
 UnitStatus = 8
 BorderAlpha = 0.200000
 RaidIconTexture = <unnamed> {
 }
 PrevRaidTargetIndex = false
 OuterTexture1 = <unnamed> {
 }
 Texture = <unnamed> {
 }
 InnerTexture = <unnamed> {
 }
 OuterTexture4 = <unnamed> {
 }
 Parent = DcrMUFsContainer {
 }
 RaidTargetIcon = false
 IsCharmed = false
 UnitGUID = "Player-3726-09D928D5"
 ToPlace = 1
 UnitName = false
 PrevCenterText = false
 Shown = true
}
Status = nil
Unit = "player"
TooltipText = ""
GUIDw

**Comment by 2072** [comment]
fixed in latest realese on Novemeber 11th
