### ISSUE TITLE
Support for Wrath of the Lich King

### ISSUE THREAD

**Issue by jar349** [2072/Decursive#9]
Hello! Now that pre-patch is live, I am going through my addons and updating them for wrath (3.4.0) and I notice that there's not yet any communication (here or on wowace) about whether you are planning to update Decursive for wrath? Please, could you let us know if that's something you are planning on supporting? Thanks!

**Comment by jazminite** [comment]
TBC version seems to work fine but please add a wrath version on Curseforge so my update tool stops with the warnings.

**Comment by 2072** [comment]
new release uploaded, I just removed/renamed 2 spell ids, not sure if there was anything else to do.
